### ISSUE TITLE
Migrating to a new HTTP backend

### ISSUE THREAD

**Issue by kittyhacker101** [kittyhacker101/KatWebX#2]
Before we can release KatWebX, we need to make sure the underlying HTTP backend is stable. Redoing the entire HTTP backend in a stable release is going to be extremely difficult, and could result in releases being delayed by months, to ensure stability.  
Actix-web (our current HTTP backend) is in the process of a 1.0 release. Migrating from 0.7 to 1.0 should be done as soon as it is stable enough. We may also need to change TLS backends, but this should be avoided if possible.
If the Actix-web 1.0 release doesn't meet our needs, all options should be carefully considered before we choose to switch backends. Rewriting KatWebX to work with a different HTTP backend could delay the release for months.

**Comment by kittyhacker101** [comment]
I've been closely watching Actix-web's development, and it looks like changing TLS backends probably won't be necessary, and the 1.0 version of Actix-web should continue to meet the needs of the project.

**Comment by kittyhacker101** [comment]
KatWebX's code is now being adapted to work with Actix-web 1.0. I'll likely have this finished within a week or two.

**Comment by kittyhacker101** [comment]
Update: Over half of KatWebX's code has been adapted so far.

**Comment by kittyhacker101** [comment]
Update: About 70% of KatWebX's code has been adapted.

**Comment by kittyhacker101** [comment]
Looks like Actix-web 1.0's websockets aren't perfect rn, so I'll probably wait until Actix-web 1.0 is finished before I upgrade the websocket code.

**Comment by kittyhacker101** [comment]
Update: There's finally some amount of documentation, so I can probably implement this now.

**Comment by iswearibehave-igotthemoooooooo** [comment]
ok boss

**Comment by iswearibehave-igotthemoooooooo** [comment]
that's cool bro
