### ISSUE TITLE
no issue

### ISSUE THREAD

**Issue by iswearibehave-igotthemoooooooo** [kittyhacker101/KatWebX#5]
everything is ok

amazing how much work you put into this even though no one uses it at the moment

**Comment by TheFlipside** [comment]
how can you be sure nobody is using it, there are no counters or statistics? what if i secretly use it for 100 web servers at my employer? nobody would know

**Comment by iswearibehave-igotthemoooooooo** [comment]
yeah i mean nobody really contributes to it and it doesn't seem to be that popular

**Comment by TheFlipside** [comment]
the next time i need a webserver i will give this a shot for sure

**Comment by iswearibehave-igotthemoooooooo** [comment]
yeah but at the moment it doesn't seem to be production ready

**Comment by iswearibehave-igotthemoooooooo** [comment]
nginx ftw !11!11!!!!

**Comment by iswearibehave-igotthemoooooooo** [comment]
@kittyhacker101 i'm sorry don't give this up, it's a great project! keep working on it!

**Comment by iswearibehave-igotthemoooooooo** [comment]
i need cat and toe pics

**Comment by iswearibehave-igotthemoooooooo** [comment]
jk

**Comment by iswearibehave-igotthemoooooooo** [comment]
anyone wanna guess the song in my name?

**Comment by iswearibehave-igotthemoooooooo** [comment]
![image](https://user-images.githubusercontent.com/53696943/62826990-3cd4ab80-bbc6-11e9-8bfb-63189bbc9742.png)
fluffy

**Comment by TheFlipside** [comment]
are you drunk or something...?

**Comment by TheFlipside** [comment]
maybe you should do this stuff on kat's discord instead on here

**Comment by iswearibehave-igotthemoooooooo** [comment]
okay, pls give link

**Comment by TheFlipside** [comment]
Kittyhacker101's Discord : Kat#3124

the link on her website "https://discord.gg/Wy2kHBg" seems to be dead though

**Comment by iswearibehave-igotthemoooooooo** [comment]
fuck

**Comment by iswearibehave-igotthemoooooooo** [comment]
in germany we have something called CYBERABWEHRZENTRUM and i think it's fucking disgusting

**Comment by iswearibehave-igotthemoooooooo** [comment]
Und immer diese triefend feuchten Damen
Wär' ich doch nur gut in Mathe, könnte ich dir sagen, wie viel es heute waren
Aber ohne den Worten von Professoren zu horchen, sind wir Idioten geworden
Wie fahr' ich nur ohne binomische Formeln
Meinen modischen Porsche?
Geh' mal die Gefahren dieses Globus erforschen
Wir sind an tropischen Orten schon fast durch Blowjobs gestorben
Guck doch, ich trag' ihn um den Hals und er ist schwer, mein Erfolg
Denn die meisten Medaillen sind auch auf der Kehrseite Gold, ah
Wir haben alle in der Schule geraucht
Und jetzt sieh uns an
Sie sagen, wir ham' uns die Zukunft verbaut
Und jetzt sieh uns an
Ihr könnt aus unser'n Fehlern hoffentlich lernen
Wir woll'n doch alle bloß 'n Job und dann sterben
Ihr könnt aus unser'n Fehlern hoffentlich lernen
Wir woll'n doch alle bloß 'n Job und dann sterben

**Comment by TheFlipside** [comment]
dude omg stop, you are a mess and spamming mine and her mail inbox with this

**Comment by iswearibehave-igotthemoooooooo** [comment]
ok

**Comment by iswearibehave-igotthemoooooooo** [comment]
Sie haben alle in der Schule geraucht
Und jetzt sieh uns an
Sie sagen, wir ham' uns die Zukunft verbaut
Und jetzt sieh uns an
Ihr könnt aus unser'n Fehlern hoffentlich lernen
Wir woll'n doch alle bloß 'n Job und dann sterben
Ihr könnt aus unser'n Fehlern hoffentlich lernen
Wir woll'n doch alle bloß 'n Job und dann sterben
Rock'n'Roll im Keta-Rausch (Keta-Rausch)
Macht sich nicht so gut im Lebenslauf (Lebenslauf)
Gangbang-Parties, Fame und Frau'n (Fame und Frau'n)
Machen sich nicht gut im Lebenslauf (Lebenslauf)
Wenn du Schore im Mercedes rauchst (Mercedes rauchst)
Macht sich das nicht gut im Lebenslauf (Lebenslauf)
Wenn du schon die dritte Leber brauchst (Leber brauchst)
Macht sich das nicht so gut im Lebenslauf
Wir haben alle in der Schule geraucht
Und jetzt sieh uns an
Sie sagen, wir ham' uns die Zukunft verbaut
Und jetzt sieh uns an
Ihr könnt aus unser'n Fehlern hoffentlich lernen
Wir woll'n doch alle bloß 'n Job und dann sterben
Ihr könnt aus unser'n Fehlern hoffentlich lernen
Wir woll'n doch alle bloß 'n Job und dann sterben

**Comment by iswearibehave-igotthemoooooooo** [comment]
Seit 5 Uhr 45 wird zurückgeschossen!

**Comment by iswearibehave-igotthemoooooooo** [comment]
btw @kittyhacker101 i need pics of your 6 cats. i love cats, i also have one.

**Comment by iswearibehave-igotthemoooooooo** [comment]
epic victory royale
![image](https://user-images.githubusercontent.com/53696943/63475054-adf44880-c47b-11e9-85d7-6758c089c73a.png)
